---
- name: Play RedHat os family tasks
  when: ansible_os_family == "RedHat"
  include_tasks: redhat.yaml

- name: Play Debian os family tasks
  when: ansible_os_family == "Debian"
  include_tasks: debian.yaml

- name: set kubelet cgroup-driver
  include: cgroup_driver.yaml

- name: set kubelet resolv-conf
  include: resolv_conf.yaml

- name: kubelet service restart
  become: yes
  systemd:
    daemon_reload: yes
    name: kubelet
    state: restarted
    enabled: yes
  ignore_errors: yes