- name: Configure Bashrc
  lineinfile:
    dest: "{{ target['home'] }}/.bashrc"
    line: "{{ item }}"
  with_items:
    - alias k='kubectl'
    - source <(kubectl completion bash)
    - complete -F __start_kubectl k