---
- name: Ensure kubernetes directory exists
  when: version.kubeadm is version('1.14','<')
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /etc/kubernetes
    - /etc/kubernetes/pki
    - /etc/kubernetes/pki/etcd

- name: copy certificate files
  when: version.kubeadm is version('1.14','<')
  become: yes
  copy:
    src: /etc/kubernetes/pki/{{ item }}
    dest: /etc/kubernetes/pki/{{ item }}
    owner: root
    group: root
    mode: 0775
  with_items:
    - etcd/ca.crt
    - etcd/ca.key
    - front-proxy-ca.crt
    - front-proxy-ca.key
    - sa.pub
    - sa.key
    - ca.crt
    - ca.key

- name: kubeadm master node join
  when: version.kubeadm is version('1.14','<')
  become: yes
  shell: "{{ join_command }} --experimental-control-plane --apiserver-advertise-address={{ ansible_host }}"
  ignore_errors: yes

- name: kubeadm master node join
  when:
    - version.kubeadm is version('1.15','<')
    - version.kubeadm is version('1.14','>=')
  become: yes
  shell: "{{ join_command }} --experimental-control-plane --certificate-key {{ cert }} --apiserver-advertise-address={{ ansible_host }}"
  ignore_errors: yes

- name: kubeadm master node join
  when: version.kubeadm is version('1.15','>=')
  become: yes
  shell: "{{ join_command }} --control-plane --certificate-key {{ cert }} --apiserver-advertise-address={{ ansible_host }}"
  ignore_errors: yes