---
- name: Create .bashrc file if no exists
  file:
    path: "{{ ansible_env.HOME }}/.bashrc"
    state: touch
    mode: 0644
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: Configure Bashrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
  with_items:
    - "alias ans='ansible'"
    - "alias anp='ansible-playbook'"
    - "alias vi='vim'"
    - "alias k='kubectl'"