---
- name: Ensure kubelet directory exists
  file:
    path: /var/lib/kubelet
    state: directory
    mode: 0700

- name: check node already in cluster
  shell: ls /var/lib/kubelet | grep config.yaml
  register: node_state
  changed_when: false
  failed_when: false

- name: play in ansible_master node
  when: ansible_hostname == groups['ansible_master'][0]
  include: init.yaml

- name: Get certificate key
  when: version['kubeadm'] is version('1.14','>=')
  set_fact:
    cert: "{{ cert.stdout_lines[-1] }}"
    
- set_fact:
    join_command: "{{ join_command.stdout }}"