---
- name: kubeadm init
  when:
    - node_state.rc != 0
    - version[1].kubeadm is version('1.16','<')
  become: yes 
  shell: |
    kubeadm init \
    --apiserver-advertise-address={{ ansible_host }} \
    --pod-network-cidr={{ pod_subnet }}
  notify: install cni network plugin

- name: kubeadm init
  when:
    - node_state.rc != 0
    - version[1].kubeadm is version('1.16','>=')
  become: yes 
  shell: |
    kubeadm init --control-plane-endpoint="{{ ansible_host }}:6443" \
    --apiserver-advertise-address={{ ansible_host }} \
    --pod-network-cidr={{ pod_subnet }}
  notify: install cni network plugin
  
- meta: flush_handlers

- name: generate a new certificate key
  when:
    - version[1].kubeadm is version('1.15','<')
    - version[1].kubeadm is version('1.14','>=')
  become: yes
  run_once: yes
  shell: kubeadm init phase upload-certs --experimental-upload-certs
  register: cert

- name: generate a new certificate key
  when: version[1].kubeadm is version('1.15','>=')
  become: yes
  run_once: yes
  shell: kubeadm init phase upload-certs --upload-certs
  register: cert

- name: generate a new join command with token
  become: yes
  run_once: yes
  shell: kubeadm token create --print-join-command
  register: join_command

- name: docker install
  when: docker_install == true
  include_role:
    name: commons/docker