---
- name: kubeadm init
  when:
    - result.rc != 0
  become: yes 
  shell: |
    kubeadm init --control-plane-endpoint="{{ ansible_host }}:6443" \
    --apiserver-advertise-address={{ ansible_host }} \
    --pod-network-cidr={{ pod_subnet }} --upload-certs
  notify: install cni network plugin
- meta: flush_handlers

- name: generate a new certificate key
  become: yes
  run_once: yes
  shell: kubeadm init phase upload-certs --upload-certs
  register: cert

- name: generate a new join command with token
  become: yes
  run_once: yes
  shell: kubeadm token create --print-join-command
  register: join_command

- name: docker install
  when: docker_install == true
  include_role:
    name: docker