---
- name: check kubernetes already installed or 6443 port already using
  shell: ps -aux | grep secure-port=6443 | grep -v grep 
  register: result
  changed_when: false
  failed_when: false

- name: kubeadm init
  when:
    - result.rc != 0
    - ansible_hostname == groups['ansible_master'][0]
  become: yes 
  shell: |
    kubeadm init --control-plane-endpoint="{{ ansible_host }}:6443" \
    --apiserver-advertise-address={{ ansible_host }} \
    --pod-network-cidr=192.168.0.0/16 --upload-certs

- name: generate a new certificate key
  when: ansible_hostname == groups['ansible_master'][0]
  become: yes
  run_once: yes
  shell: kubeadm init phase upload-certs --upload-certs
  register: cert

- name: generate a new join command with token
  when: ansible_hostname == groups['ansible_master'][0]
  become: yes
  run_once: yes
  shell: kubeadm token create --print-join-command
  register: join_command

- set_fact:
    cert: "{{ cert.stdout_lines[-1] }}"
    
- set_fact:
    join_command: "{{ join_command.stdout }}"