---
- name: check kubernetes already installed or 6443 port already using
  shell: ps -aux | grep secure-port=6443 | grep -v grep 
  register: result
  changed_when: false
  failed_when: false

- name: play in ansible_master node
  when: ansible_hostname == groups['ansible_master'][0]
  include: init.yaml

- set_fact:
    cert: "{{ cert.stdout_lines[-1] }}"
    
- set_fact:
    join_command: "{{ join_command.stdout }}"