---
- name: Install sshpass for Authentication (RHEL/CentOS)
  when: ansible_os_family == "RedHat"
  become: yes
  yum:
    name: sshpass
    state: present

- name: Install sshpass for Authentication (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  become: yes
  apt:
    name: sshpass
    state: present

- name: check ssh keypair exists
  become: yes
  stat:
    path: "{{ ansible_env['HOME'] }}/.ssh/id_rsa"
  register: keypair

- when: not keypair.stat.exists
  block:
  - name: generate openssh keypair with the default values (4096 bits, rsa)
    become: yes
    openssh_keypair:
      path: "{{ ansible_env['HOME'] }}/.ssh/id_rsa"
      owner: "{{ ansible_env['USER'] }}"
      group: "{{ ansible_env['USER'] }}"

  - name: change owner of the generated pub key
    become: yes
    file:
      path: "{{ ansible_env['HOME'] }}/.ssh/id_rsa.pub"
      owner: "{{ ansible_env['USER'] }}"
      group: "{{ ansible_env['USER'] }}"

- name: execute key.sh
  shell: "{{ lookup('template', 'key.j2') }}"