---
- name: Install sshpass for Authentication (RHEL/CentOS)
  when: ansible_os_family == "RedHat"
  become: yes
  yum:
    name: sshpass
    state: present

- name: Install sshpass for Authentication (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  become: yes
  apt:
    name: sshpass
    state: present

- name: create key.sh file
  template:
    src: "key.j2"
    dest: "{{ ansible_env.HOME }}/key.sh"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0777

- name: execute key.sh file
  command: "{{ ansible_env.HOME }}/key.sh"

- when: root_login == true
  set_fact:
    local_home : "{{ ansible_env.HOME }}"

- name: execute key.sh file on root
  when: root_login == true
  become: yes
  command: "{{ local_home }}/key.sh"

- name: remove key.sh file
  file:
    state: absent
    path: "{{ ansible_env.HOME }}/key.sh"