---
- name: Install git latest
  when: version == 'latest'
  become: yes
  apt:
    update_cache: yes
    name: git
    state: latest

- name: Install git specific version
  when: version != 'latest'
  become: yes
  apt:
    update_cache: yes
    name: git={{ version }}
    state: present