---
- name: Install git latest
  when: version == 'latest'
  become: yes
  yum:
    name: git
    state: latest

- name: Install git specific version
  when: version != 'latest'
  become: yes
  yum:
    name: git-{{ version }}
    state: present