---
- name: Disable swap for current session
  command: swapoff -a
  become: true

- name: swapoff permanent
  become: yes
  replace:
    dest: /etc/fstab
    regexp: '(^\s*UUID=)((?:\w+-){4}\w+\s)(\w+\s+)(swap)'
    replace: '#\1\2\3\4'
    backup: yes

- name: Create container-runtime.conf file if no exists
  become: yes
  file:
    path: /etc/modules-load.d/container-runtime.conf
    state: touch
    mode: 0644
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: write modules in container-runtime.conf file
  become: yes
  lineinfile:
    dest: /etc/modules-load.d/container-runtime.conf
    line: "{{ item }}"
  with_items:
    - overlay
    - br_netfilter

- name: Load overlay & br_netfilter module
  become: yes
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Create 99-kubernetes-cri.conf file if no exists
  become: yes
  file:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    state: touch
    mode: 0644
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: apply sysctl entries
  become: yes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: yes
  with_items:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.ipv4.ip_forward', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }