---
- name: kubeadm master node join
  when:
    - result.rc != 0
    - ansible_hostname in groups['master']
    - ansible_hostname != groups['ansible_master'][0]
  become: yes
  shell: "{{ join_command }} --control-plane --certificate-key {{ cert }} --apiserver-advertise-address={{ ansible_host }}"

- name: kubeadm worker node join
  when:
    - result.rc != 0
    - ansible_hostname in groups['worker']
  become: yes
  shell: "{{ join_command }}"