---
local_home: "{{ lookup('env','HOME') }}"
local_user: "{{ lookup('env','USER') }}"

# https://kubernetes.io/ko/docs/setup/production-environment/container-runtimes/
systemd_cgroup: "true"

docker_registry: yes