---
local_home: "{{ lookup('env','HOME') }}"
local_user: "{{ lookup('env','USER') }}"

# https://kubernetes.io/ko/docs/setup/production-environment/container-runtimes/
cgroup_driver: systemd

docker_registry: yes