---
local:
  user: "{{ lookup('env','USER') }}"
  home: "{{ lookup('env','HOME') }}"

target:
  user: "{{ ansible_env['USER'] }}"
  home: "{{ ansible_env['HOME'] }}"

systemd_cgroup: yes  # https://kubernetes.io/ko/docs/setup/production-environment/container-runtimes/
systemd_resolved: yes
nameservers:
  - 8.8.8.8
  - 8.8.4.4

docker_registry: yes