---
- name: Install git (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  become: yes
  apt:
    name: "git"
    state: present

- name: Install vim-enhanced (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  become: yes
  apt:
    name: "vim"
    state: present