---
- name: Create .bashrc file if no exists
  when: alias == true
  file:
    path: "{{ ansible_env.HOME }}/.bashrc"
    state: touch
    mode: 0644
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: Configure Bashrc(ansible)
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
  with_items:
    - "alias ans='ansible'"
    - "alias anp='ansible-playbook'"

- name: Configure Bashrc(vim)
  when: '"vim" in packages'
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "alias vi='vim'"

- name: Play RedHat os family tasks
  when: ansible_os_family == "RedHat"
  include_tasks: redhat.yaml

- name: Play Debian os family tasks
  when: ansible_os_family == "Debian"
  include_tasks: debian.yaml

- name: Install vim plugins
  when: vim_plugins == true
  include_tasks: vim_plugin.yaml