---
- name: Download binaries
  get_url:
    url: https://github.com/containerd/containerd/releases/download/v{{ version.containerd }}/containerd-{{ version.containerd }}-linux-amd64.tar.gz
    dest: "{{ ansible_env.HOME }}/Downloads/containerd.tar"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644


- name: Unarchive containerd binaries archive
  unarchive:
    src: "{{ ansible_env.HOME }}/Downloads/containerd.tar"
    dest: "{{ ansible_env.HOME }}/Downloads"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: Copy containerd binaries in PATH
  become: yes
  copy:
    src: "{{ local_home }}/Downloads/bin/"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755

- name: Add containerd service
  become: yes
  copy:
    src: containerd.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644

- name: Ensure containerd config folder exists
  become: yes
  file:
    path: /etc/containerd
    state: directory
    mode: 0750

- name: Generate default containerd config file
  become: yes
  template:
    src: config.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: 0644
  notify: containerd_restart
- meta: flush_handlers