---
- name: Install latest packages needed to use the Kubernetes
  when: version[0].latest == true
  become: yes
  apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
    state: latest

- name: Install specific version packages needed to use the Kubernetes
  when: version[0].latest == false
  become: yes
  apt:
    update_cache: yes
    name:
      - apt-transport-https={{ version[0].apt-transport-https }}
      - ca-certificates={{ version[0].ca-certificates }}
    state: present

- name: Download the Google Cloud public signing key
  become: yes
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    owner: root
    group: root
    mode: 0644

- name: Create Kubernetes apt repository list file if no exists
  become: yes
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: touch
    mode: 0644
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: write Kubernetes apt repository in list file
  become: yes
  lineinfile:
    dest: /etc/apt/sources.list.d/kubernetes.list
    line: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main

- name: Install latest kubelet, kubeadm, kubectl
  when: version[1].latest == true
  become: yes
  apt:
    update_cache: yes
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: latest

- name: Install specific version kubelet, kubeadm, kubectl
  when: version[1].latest == false
  become: yes
  apt:
    update_cache: yes
    name:
      - kubelet={{ version[1].kubelet }}
      - kubeadm={{ version[1].kubeadm }}
      - kubectl={{ version[1].kubectl }}
    state: present

- name: Hold kubelet, kubeadm, kubectl
  become: yes
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl

