- name: Install bash-completion (RHEL/CentOS)
  when: ansible_os_family == "RedHat"
  become: yes
  yum:
    name: bash-completion
    state: present

- name: Install bash-completion (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  become: yes
  apt:
    name: bash-completion
    state: present