---
- name: ansible ssh settings
  # hosts: localhost
  hosts: cluster
  serial: 1
  roles:
    - ssh
    
- name: add hosts in hosts file
  hosts: ansible_clients
  tasks:
    - include_tasks: tasks/hosts.yaml

- name: custom settings(root)
  become: yes
  hosts: cluster
  roles:
    - custom/alias

- name: custom settings
  hosts: cluster
  roles:
    - custom/alias
    - custom/git
    - custom/vim

- name: custom settings
  hosts: cluster
  gather_facts: no
  roles:
    - custom/motd

- name: install container runtime
  hosts: cluster
  vars:
    runtime: containerd
    # runtime: docker
    # runtime: cri-o
  roles:
    - runtime