---
- name: ansible ssh settings
  hosts: cluster
  serial: 1
  roles:
    - ssh

- name: kubernetes install
  hosts: cluster
  vars:
    runtime: containerd
  roles:
    - { role: runtime/containerd, when: runtime == 'containerd' }
    - { role: runtime/docker, when: runtime == 'docker' }
    - { role: runtime/cri-o, when: runtime == 'cri-o' }
    - kubernetes/preinstall
    - kubernetes/init
    - kubernetes/join
- hosts: master
  roles:
    - kubernetes/config

- name: custom settings
  hosts: cluster
  roles:
    - custom/alias/ansible
    - custom/alias/vim
    - custom/alias/kubernetes
    - custom/git
    - custom/vim/vim
    - custom/vim/vim-plugins
    - custom/vim/vim-custom
    - custom/motd

- name: custom settings(root)
  become: yes
  hosts: cluster
  roles:
    - custom/alias/ansible
    - custom/alias/vim
    - custom/alias/kubernetes
    - custom/vim/vim-custom
