---
- name: ansible ssh settings
  hosts: cluster
  serial: 1
  roles:
    - ssh

- name: kubernetes install, custom settings
  hosts: cluster
  roles:
    - runtime
    - kubernetes
    - custom/alias/ansible
    - custom/alias/vim
    - custom/alias/docker
    - custom/alias/kubernetes
    - custom/git
    - custom/vim/vim
    - custom/vim/vim-plugins
    - custom/vim/vim-custom
    - custom/motd

- name: custom settings(root)
  become: yes
  hosts: cluster
  roles:
    - custom/alias/ansible
    - custom/alias/vim
    - custom/alias/docker
    - custom/alias/kubernetes
    - custom/vim/vim-custom
