---
- name: ansible ssh settings
  hosts: cluster
  gather_facts: yes
  serial: 1
  roles:
    - role: ssh
    - become: yes
      role: commons/setup
    - role: ssh

- name: kubernetes install, custom settings
  hosts: cluster
  gather_facts: no
  become: yes
  roles:
    - become: no
      role: commons/setup
    - role: runtime
    - role: kubernetes
    - role: custom/alias/ansible
    - role: custom/alias/vim
    - role: custom/alias/docker
    - role: custom/alias/kubernetes
    - role: custom/git
    - role: custom/vim/vim
    - role: custom/vim/vim-plugins
    - role: custom/vim/vim-custom
    - role: custom/motd
    - role: commons/setup
    - role: custom/alias/ansible
    - role: custom/alias/vim
    - role: custom/alias/docker
    - role: custom/alias/kubernetes
    - role: custom/vim/vim-plugins
    - role: custom/vim/vim-custom