---
- name: Install vim-enhanced latest
  when: version == 'latest'
  become: yes
  apt:
    name: vim
    state: latest

- name: Install vim-enhanced specific version
  when: version != 'latest'
  become: yes
  apt:
    name: vim={{ version }}
    state: present